gestione/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


app_name = "gestione"

urlpatterns = [
    path('mezzo/<int:pk>/', MezzoDetailView.as_view(), name='mezzo-detail'),
    path('listamezzi/', MezzoListView.as_view(), name='mezzo-list'),
    path('accessorio/<int:pk>/', AccDetailView.as_view(), name='acc-detail'),
    path('listaacc/', AccListView.as_view(), name='acc-list'),
    path('creamezzo/', login_required(CreateMezzoView.as_view()), name="mezzo-crea"),
    path('creaimmmacc/<int:car_id>/', login_required(CreateImmaginiMacchinaView.as_view()), name="IM-crea"),
    path('creaaccessorio/', login_required(CreateAccView.as_view()), name="acc-crea"),
    path('creaIA/<int:acc_id>/', login_required(CreateImmaginiAccessorioView.as_view()), name="IA-crea"),
    path('dashboard/', login_required(dashbord), name="dashboard"),
    path('venditore/oggetti/mod/', login_required(oggetti_venditore_mod), name='ogg-vend-mod'),
    path('venditore/oggetti/vis/', login_required(oggetti_venditore_vis), name='ogg-vend-vis'),
    path('venditore/oggetti/del/', login_required(oggetti_venditore_del), name='ogg-vend-del'),
    path('venditore/oggetti/update/mezzo/<int:pk>/', login_required(MezzoUpdateView.as_view()), name='update_mezzo'),
    path('venditore/oggetti/update/accessorio/<int:pk>/', login_required(AccessorioUpdateView.as_view()), name='update_accessorio'),
    path('venditore/oggetti/delete/mezzo/<int:pk>/', login_required(MezzoDeleteView.as_view()), name='delete_mezzo'),
    path('venditore/oggetti/delete/accessorio/<int:pk>/', login_required(AccessorioDeleteView.as_view()), name='delete_accessorio')
]

tecweb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from .initcmds import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^/$|^home/$", home_page, name="home"),
    path('gestione/', include('gestione.urls')),
    path('get_filtered_mezzi/', get_filtered_mezzi, name='get_filtered_mezzi'),
    path('get_filtered_acc/', get_filtered_acc, name='get_filtered_acc'),
    path("register/", register_request, name="register"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name="logout"),
    path('authHome/', authHome_page, name="authHome_page"),
    path('add_to_favorites/<str:object_type>/<int:object_id>/', add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<str:object_type>/<int:object_id>/', remove_from_favorites, name='remove_from_favorites'),
    path('favoriti/', favorite_objects, name='favoriti'),
    path('add_to_cart/<str:object_type>/<int:object_id>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<str:object_type>/<int:object_id>/', remove_from_cart, name='remove_from_cart'),
    path('carrello/', view_cart, name='carrello'),
    path('spedizione/', login_required(SpedCreateView.as_view()) , name='spedizione'),
    path('spedizionilist/', view_spedizioni, name='spedizioni_list'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#erase_db()
#init_db()

gestione/models.py
from django.db import models
from django.db.models import Model
from django.contrib.auth.models import User

class Venditore(Model):
    cf = models.CharField(max_length=16, primary_key=True)
    nome = models.CharField(max_length=50)
    iban = models.CharField(max_length=34)
    telefono = models.CharField(max_length=16)
    pec = models.CharField(max_length=40, null=True)
    mail = models.CharField(max_length=319)
    indirizzo = models.CharField(max_length=50)
    citta = models.CharField(max_length=50)
    provincia = models.CharField(max_length=50)
    venditore = models.ForeignKey(to=User, on_delete=models.CASCADE, unique=False)

    class Meta:
        verbose_name_plural = "Venditori"

class Mezzo(Model):
    vin = models.CharField(max_length=17, unique=True)
    moto = models.BooleanField()
    marca = models.CharField(max_length=20)
    modello = models.CharField(max_length=35)
    prezzo = models.PositiveIntegerField()
    data_fabbricazione = models.DateField()
    kilometraggio = models.PositiveIntegerField()
    colore = models.CharField(max_length=15)
    num_proprietari = models.PositiveSmallIntegerField()
    venditore = models.ForeignKey(to=Venditore, on_delete=models.CASCADE, unique=False)

    class Meta:
        verbose_name_plural = "Mezzi"

class ImmaginiMacchina(Model):
    def uploadTo(istance, filename):
        return f"{istance.car_id.id}/{filename}"
    
    car_id = models.OneToOneField(to=Mezzo, on_delete=models.CASCADE, primary_key=True, unique=True)
    fronte = models.ImageField(upload_to = uploadTo)
    retro = models.ImageField(upload_to = uploadTo, null=True, blank=True)
    interni = models.ImageField(upload_to = uploadTo, null=True, blank=True)
    
    class Meta:
        verbose_name_plural = "Immagini Macchine"

class Accessorio(Model):
    per_moto = models.BooleanField()
    nome = models.CharField(max_length=20)
    descrizione = models.TextField(max_length=500)
    prezzo = models.FloatField()
    venditore = models.ForeignKey(to=Venditore, on_delete=models.CASCADE, unique=False)

    class Meta:
        verbose_name_plural = "Accessori"

class ImmaginiAccessorio(Model):
    def uploadTo(istance, filename):
        return f"accessori/{istance.acc_id.id}/{filename}"
    
    acc_id = models.OneToOneField(to=Accessorio, on_delete=models.CASCADE, primary_key=True, unique=True)
    foto1 = models.ImageField(upload_to = uploadTo)
    foto2 = models.ImageField(upload_to = uploadTo, null=True, blank=True)
    foto3 = models.ImageField(upload_to = uploadTo, null=True, blank=True)
    
    class Meta:
        verbose_name_plural = "Immagini Accessori"

class FavouriteMezzo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mezzo = models.ForeignKey(Mezzo, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'mezzo')
        verbose_name_plural = "Mezzi favoriti"

class FavouriteAccessorio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    acc = models.ForeignKey(Accessorio, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'acc')
        verbose_name_plural = "Accessori favoriti"

class OggettoCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mezzo = models.ForeignKey('Mezzo', on_delete=models.CASCADE, null=True)
    accessorio = models.ForeignKey('Accessorio', on_delete=models.CASCADE, null=True)

class Carrello(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OggettoCart, related_name='cerrello')

    def add_to_cart(self, item_type, item_id):
        try:
            if item_type == 'mezzo':
                item = Mezzo.objects.get(pk=item_id)
                cart_item, created = OggettoCart.objects.get_or_create(user=self.user, mezzo=item)
            elif item_type == 'accessorio':
                item = Accessorio.objects.get(pk=item_id)
                cart_item, created = OggettoCart.objects.get_or_create(user=self.user, accessorio=item)
            
            self.items.add(cart_item)
            
            return True
        except (Mezzo.DoesNotExist, Accessorio.DoesNotExist):
            return False

    def remove_from_cart(self, item_type=None, item_id=None):
        try:
            if item_type == 'mezzo':
                item = Mezzo.objects.get(pk=item_id)
                cart_item = OggettoCart.objects.filter(user=self.user, mezzo=item).first()
            elif item_type == 'accessorio':
                item = Accessorio.objects.get(pk=item_id)
                cart_item = OggettoCart.objects.filter(user=self.user, accessorio=item).first()

            if cart_item:
                cart_item.delete()
            return True
        except:
            return False
        
    def get_items(self):
        return self.items.all()

    def get_costo_tot(self):
        costo_tot=0
        for item in self.get_items():
            if(item.mezzo):
                costo_tot += item.mezzo.prezzo
            else:
                costo_tot += item.accessorio.prezzo
        return costo_tot
    
    def clear_cart(self):
        self.items.clear()
    
    class Meta:
        verbose_name_plural = "Carrelli"

class Spedizione(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    via = models.TextField()
    citta = models.CharField(max_length=50)
    CAP = models.CharField(max_length=20)
    stato = models.CharField(max_length=50)
    is_appuntamento = models.BooleanField()
    dataora = models.DateTimeField(null=True, blank=True)
    successful = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Spedizioni"

gestione/forms.py
from django import forms
from .models import Mezzo

class MezzoForm(forms.ModelForm):
    class Meta:
        model = Mezzo
        fields = "__all__"  

    data_fabbricazione = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

gestione/views.py
from .models import Mezzo, ImmaginiMacchina, Accessorio, ImmaginiAccessorio, Venditore
from django.views.generic import DetailView, ListView, CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView
from .forms import MezzoForm
from django.core.exceptions import PermissionDenied

class MezzoListView(ListView):
    model = Mezzo
    template_name="gestione/listaMezzi.html"


class MezzoDetailView(DetailView):
    model = Mezzo
    template_name = 'gestione/dettagliMezzo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['immagini_mezzo'] = ImmaginiMacchina.objects.filter(car_id=self.object.id)
        context['venditore'] = self.object.venditore
        return context
    
class AccListView(ListView):
    model = Accessorio
    template_name="gestione/listaAcc.html"


class AccDetailView(DetailView):
    model = Accessorio
    template_name = "gestione/dettagliAcc.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['immagini_acc'] = ImmaginiAccessorio.objects.filter(acc_id_id=self.object.id)
        context['venditore'] = self.object.venditore
        return context
    
class CreateMezzoView(CreateView):
    model = Mezzo
    template_name = "gestione/creaMezzo.html"
    form_class = MezzoForm
        
    def form_valid(self, form):
        response = super().form_valid(form)
        return redirect(reverse_lazy('gestione:IM-crea', kwargs={'car_id': self.object.pk}))

    def get_success_url(self):
        return reverse('gestione:mezzo-list')  


class CreateImmaginiMacchinaView(CreateView):
    model = ImmaginiMacchina
    fields = "__all__" 
    template_name = 'gestione/creaImmMacc.html' 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['car_id'] = self.kwargs['car_id']
        return context


    def form_valid(self, form):
        form.instance.car_id_id = self.kwargs['car_id']
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse('gestione:mezzo-list')
    
class CreateAccView(CreateView):
    model = Accessorio
    template_name = "gestione/creaAccessorio.html"
    fields = "__all__"
        
    def form_valid(self, form):
        response = super().form_valid(form)
        return redirect(reverse_lazy('gestione:IA-crea', kwargs={'acc_id': self.object.pk}))

    def get_success_url(self):
        return reverse('gestione:acc-list')  


class CreateImmaginiAccessorioView(CreateView):
    model = ImmaginiAccessorio
    fields = "__all__" 
    template_name = 'gestione/creaImmAcc.html' 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['acc_id'] = self.kwargs['acc_id']
        return context


    def form_valid(self, form):
        form.instance.acc_id_id = self.kwargs['acc_id']
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse('gestione:acc-list')
    
def dashbord(request):
    return render(request, "gestione/dashboard.html")

def oggetti_venditore_mod(request):
    venditore = Venditore.objects.get(venditore_id=request.user)
    mezzo_list = Mezzo.objects.filter(venditore=venditore)
    accessorio_list = Accessorio.objects.filter(venditore=venditore)

    context = {
        'mezzo_list': mezzo_list,
        'accessorio_list': accessorio_list,
    }
    return render(request, 'gestione/ModoggVenditori.html', context)

def oggetti_venditore_vis(request):
    venditore = Venditore.objects.get(venditore_id=request.user)
    mezzo_list = Mezzo.objects.filter(venditore=venditore)
    accessorio_list = Accessorio.objects.filter(venditore=venditore)

    context = {
        'mezzo_list': mezzo_list,
        'accessorio_list': accessorio_list,
    }
    return render(request, 'gestione/listaprod.html', context)

class MezzoUpdateView(UpdateView):
    model = Mezzo
    template_name = 'gestione/updateMezzo.html'
    fields =  ["moto", "marca", "modello", "prezzo", "data_fabbricazione",
               "kilometraggio", "colore", "num_proprietari"]
    def get_success_url(self):
        return reverse('gestione:dashboard')  

class AccessorioUpdateView(UpdateView):
    model = Accessorio
    template_name = 'gestione/updateAccessorio.html'
    fields =   ["per_moto", "nome", "descrizione", "prezzo"]
    
    def get_success_url(self):
        return reverse('gestione:dashboard')  
    
def oggetti_venditore_del(request):
    venditore = Venditore.objects.get(venditore_id=request.user)
    mezzo_list = Mezzo.objects.filter(venditore=venditore)
    accessorio_list = Accessorio.objects.filter(venditore=venditore)

    context = {
        'mezzo_list': mezzo_list,
        'accessorio_list': accessorio_list,
    }
    return render(request, 'gestione/listDel.html', context)

class MezzoDeleteView(DeleteView):
    model = Mezzo
    template_name = 'gestione/delProd.html'

    def get_success_url(self):
        return reverse('gestione:dashboard')  

    def get_queryset(self):
        return Mezzo.objects.filter(venditore__venditore=self.request.user)
    
    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.venditore.venditore_id != self.request.user.id:
            raise PermissionDenied
        return obj

class AccessorioDeleteView(DeleteView):
    model = Accessorio
    template_name = 'gestione/delProd.html'

    def get_success_url(self):
        return reverse('gestione:dashboard')  

    def get_queryset(self):
        return Mezzo.objects.filter(venditore__venditore=self.request.user)
    
    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        print(obj)
        if obj.venditore.venditore_id != self.request.user.id:
            raise PermissionDenied
        return obj

gestione/templates/gestione/ModoggVenditori.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Dashbord venditore
{% endblock %}
{%block content%}
<h1>I tuoi Oggetti:</h1>
<h2>I tuoi mezzi:</h2>
<ul>
    {% for mezzo in mezzo_list %}
        <li>
            <a href="{% url 'gestione:update_mezzo' mezzo.pk %}">
                {{ mezzo.marca }} {{ mezzo.modello }} ({{mezzo.vin }})
            </a>
        </li>
    {% endfor %}
</ul>

<h2>I tuoi accessori</h2>
<ul>
    {% for accessorio in accessorio_list %}
        <li>
            <a href="{% url 'gestione:update_accessorio' accessorio.pk %}">
                {{ accessorio.nome }} {{ accessorio.id }}
            </a>
        </li>
    {% endfor %}
</ul>
    <a style="font-size:24; color: black" href="{% url 'gestione:dashboard' %}" style="margin-top: 25px;">Torna alla dashboard</a>
{%endblock%}

gestione/templates/gestione/creaAccessorio.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Inserimento mezzo {{ object.id }}
{% endblock %}

{%block head%}
    {%load humanize%}
    {%load static%}
{% endblock %}

{% block content %}
    <h1 style="font-size:36" align="center">
        INSERIMENTO DELL'ACCESSORIO NEL DATABASE
    </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    <a style="font-size:24; color: black" href="{% url 'gestione:acc-list' %}" style="margin-top: 25px;">Torna alla lista degli accessori!</a>
{% endblock %}

gestione/templates/gestione/creaImmAcc.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Inserimento immagini accessorio {{ object.id }}
{% endblock %}

{%block head%}
    {%load static%}
{% endblock %}

{% block content %}
    <h1 style="font-size:36" align="center">
        INSERIMENTO DELLE IMMAGINI DELL'ACCESSORIO
    </h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="acc_id" value="{{ acc_id }}">
        {{ form.foto1 }}
        {{ form.foto2 }}
        {{ form.foto3 }}
        <button type="submit">Create</button>
    </form>
    <a style="font-size:24; color: black" href="{% url 'gestione:mezzo-list' %}" style="margin-top: 25px;">Torna alla lista dei mezzi</a>
{% endblock %}

gestione/templates/gestione/creaImmMacc.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Inserimento mezzo {{ object.id }}
{% endblock %}

{%block head%}
    {%load humanize%}
    {%load static%}
{% endblock %}

{% block content %}
    <h1 style="font-size:36" align="center">
        INSERIMENTO DELLE IMMAGINI DELLA MACCHINA
    </h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="car_id" value="{{ car_id }}">
        {{ form.fronte }}
        {{ form.interni }}
        {{ form.retro }}
        <button type="submit">Create</button>
    </form>
    <a style="font-size:24; color: black" href="{% url 'gestione:mezzo-list' %}" style="margin-top: 25px;">Torna alla lista dei mezzi</a>
{% endblock %}

gestione/templates/gestione/creaMezzo.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Inserimento mezzo {{ object.id }}
{% endblock %}

{%block head%}
    {%load humanize%}
    {%load static%}
{% endblock %}

{% block content %}
    <h1 style="font-size:36" align="center">
        INSERIMENTO DEL MEZZO NEL DATABASE
    </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

gestione/templates/gestione/dashboard.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Dashbord venditore
{% endblock %}

{%block head%}
    {%load static%}
    <style>
        body{
            background-color: #DFF2EF;
            display: 
        }

        .container {
            padding: 20px;
            display: flex;
            flex-wrap: wrap;
            height: 90%;
            width: 90%;
          }
          
          .item {
            line-height: 300px;
            margin: 20px;
            padding: 2%;
            width: 40%;
            height: 40%;
            border: 1px solid #eee;
            background-color: white;
          }

          .container a{
            font-size: 40;
            color:black;
            text-decoration: none;
          }
    </style>
{% endblock %}

{% block content %}
<div class="container" align="center">
    <div class="item"> 
        <a href="{%url "gestione:mezzo-crea"%}">
            Inserisci mezzo
        </a>
    </div>
    <div class="item">
        <a href="{%url "gestione:acc-crea"%}">
            Inserisci accessorio
        </a>
    </div>
    <div class="item">
        <a href="{%url "gestione:ogg-vend-mod"%}">
            Modifica prodotto
        </a>
    </div>
    <div class="item">
        <a href="{%url "gestione:ogg-vend-del"%}">
            Elimina prodotto
        </a>
    </div>
    <div>
        <a style="font-size:24; color: black" href="{% url 'gestione:ogg-vend-vis' %}" style="margin-top: 25px;">Guarda i tuoi prodotti!</a>
    </div>
</div>

{% endblock %}

gestione/templates/gestione/delProd.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Confirmation</title>
</head>
<body>
    <h1>Delete {{ object }}</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
</body>
</html>

gestione/templates/gestione/dettagliAcc.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Dettaglio accessorio {{ object.id }}
{% endblock %}

{%block head%}
    {%load humanize%}
    {%load static%}
    <style>
        body{
            background-image: url("{%static "/imgs/a.png"%}");
        }
        .content{
            width: 100%;
            height: 100%;
        }

        .content div{
            background-image: url("{%static "/imgs/a.png"%}");
            margin-top:25px;
        }
    </style>
{% endblock %}

{% block content %}
<div class="content">
    <h1 style="color: white; font-size:36" align="center">
        DETTAGLI DI {{ object.nome }}
    </h1>
    <p style="font-size: 28; font-weight: bold; color: blue"><u>Prezzo: {{ object.prezzo|intcomma }} €</u></p>
    {%if object.per_moto %}
        <p style="font-size: 22;">
            Costruito per le moto
        </p>
    {% else %}
        <p style="font-size: 22;">
            Costruito per le macchine
        </p>
    {% endif %}
    
    <p  style="font-size: 22;">Descrizone del prodotto: <br/> {{ object.descrizione }}</p>

    <h2>Immagini del Mezzo:</h2>
    
    {% for immagine in immagini_acc %}

        <div align="center">
            <img src="{{ immagine.foto1.url }}" alt="Immagine Mezzo"  /> 
        </div>

        {%if immagine.foto2.url != ''%}
        <div align="center">
            <img src="{{ immagine.foto2.url }}" alt="Immagine Mezzo"  /> 
        </div>
        {%endif%}

        {%if immagine.foto3.url != ''%}
        <div align="center">
            <img src="{{ immagine.foto3.url }}" alt="Immagine Mezzo"  /> 
        </div>
        {%endif%}

    {% endfor %}
    
    <div>
        <h2>Contatta il venditore:</h2>
        <p>Nome: {{ venditore.nome }}</p>
        <p>Telefono: {{ venditore.telefono }}</p>
        <p>mail: <a href="mailto:{{venditore.mail}} ">{{ venditore.mail }}</a></p>
        <p>PEC: {{ venditore.pec }}</p>
        <p>Indirizzo: {{ venditore.indirizzo }} </p>
        <p>Città: {{ venditore.citta }}</p>
        <p>Provincia: {{ venditore.provincia }}</p>
        <p>CF: {{ venditore.cf }}</p>
    </div>

    <div align="left">
        <a style="font-size:24; color: black" href="{% url 'gestione:acc-list' %}" style="margin-top: 25px;">Torna alla lista dei mezzi</a>
        <a style="font-size:24; color: black" href="{% url 'gestione:dashboard' %}" style="margin-top: 25px;">Torna alla dashboard</a>
    </div>
</div>
{% endblock %}

gestione/templates/gestione/listaAcc.html
<html>
    <body>
        <h1 align="center">
            Benvenuto nella lista di tutti gli accessori di<br> Dag Dal Gas
        </h1>
    {% for p in object_list %}
        <ul>
            <a href="{% url 'gestione:acc-detail' p.id %}">
                {{ p.id }}: {{ p.nome }}
                {%if p.per_moto %}
                    (per moto)
                {%else%}
                    (per macchine)
                {% endif %}
            </a>
        </ul>
    {% endfor %}
    <a style="font-size:24; color: black" href="{% url 'gestione:dashboard' %}" style="margin-top: 25px;">Torna alla dashboard</a>
    </body>
</html>

gestione/templates/gestione/listaMezzi.html
<html>
    <body>
        <h1 align="center">
            Benvenuto nella lista di tutti i mezzi di<br> Dag Dal Gas
        </h1>
    {% for p in object_list %}
        <ul>
            <a href="{% url 'gestione:mezzo-detail' p.id %}">
                {{ p.id }}: {{ p.marca }} {{ p.modello }} 
            </a>
        </ul>
    {% endfor %}
    <a style="font-size:24; color: black" href="{% url 'gestione:dashboard' %}" style="margin-top: 25px;">Torna alla dashboard</a>
    </body>
</html>

gestione/templates/gestione/listaprod.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Dashbord venditore
{% endblock %}
{%block content%}
<h1>I tuoi Oggetti:</h1>
<h2>I tuoi mezzi:</h2>
<ul>
    {% for mezzo in mezzo_list %}
        <li>
            <a href="{% url 'gestione:mezzo-detail' mezzo.pk %}">
                {{ mezzo.marca }} {{ mezzo.modello }} ({{mezzo.vin }})
            </a>
        </li>
    {% endfor %}
</ul>

<h2>I tuoi accessori</h2>
<ul>
    {% for accessorio in accessorio_list %}
        <li>
            <a href="{% url 'gestione:acc-detail' accessorio.pk %}">
                {{ accessorio.nome }}
            </a>
        </li>
    {% endfor %}
</ul>
    <a style="font-size:24; color: black" href="{% url 'gestione:dashboard' %}" style="margin-top: 25px;">Torna alla dashboard</a>
{%endblock%}

gestione/templates/gestione/oggvenditori.html
{% extends 'gestione/common.html' %}
{% block title%} 
    Dashbord venditore
{% endblock %}
{%block content%}
<h1>I tuoi Oggetti:</h1>
<h2>I tuoi mezzi:</h2>
<ul>
    {% for mezzo in mezzo_list %}
        <li>
            <a href="{% url 'gestione:update_mezzo' mezzo.pk %}">
                {{ mezzo.marca }} {{ mezzo.modello }}
            </a>
        </li>
    {% endfor %}
</ul>

<h2>I tuoi accessori</h2>
<ul>
    {% for accessorio in accessorio_list %}
        <li>
            <a href="{% url 'gestione:update_accessorio' accessorio.pk %}">
                {{ accessorio.nome }}
            </a>
        </li>
    {% endfor %}
</ul>
{%endblock%}

gestione/templates/gestione/updateAccessorio.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Mezzo</title>
</head>
<body>
    <h1>Update Mezzo</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Mezzo</button>
    </form>
    <br>
    <a href="{% url 'gestione:dashboard' %}">Torna alla dashboard</a>
</body>
</html>